[package]
name = "rust"
version = "0.1.0"
authors = ["Eric Mertens <emertens@gmail.com>"]
edition = '2018'

[dependencies]
scan_fmt = "^0.1"

[[bin]]
name = "day01"
path = "src/day01/main.rs"

[[bin]]
name = "day02"
path = "src/day02/main.rs"

[[bin]]
name = "day07"
path = "src/day07/main.rs"
